### ISSUE TITLE
Pixel_Shuffle

### ISSUE THREAD

**Issue by NessAupera** [hahnyuan/nn_tools#8]
Thank you for this helpful tool.
It'd be very helpful for computer vision applications to have pixel_shuffle support in pytorch_to_caffe.

Cheers,
Ness

**Comment by ChenYingpeng** [comment]
@NessAupera Hi, Did you slove this problem? I met the same problem.

**Comment by hahnyuan** [comment]
Hi,
There is no direct PixelShuffle implementation in Caffe. I think this could be difficult to do pixel_shuffle using the layers of official version of Caffe, because we cannot implement the pixel shuffle without permute or transpose layer. 
I think you could implement this PixelShuffle layer yourself in Caffe, or using SSD branch of caffe (https://github.com/weiliu89/caffe/tree/ssd) which implements a permute layer to assemble a PixelShuffle layer.

Zhihang

**Comment by NessAupera** [comment]
> @NessAupera Hi, Did you slove this problem? I met the same problem.
